import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Web3Provider } from "@/app/providers/Web3Provider"
import RecoilProvider from "@/app/providers/RecoilProvider"
import NavBar from "@/components/layout/NavBar"
import Footer from "@/components/layout/footer"
import { Toaster } from "@/components/ui/sonner"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RPS-LS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          <Web3Provider>
            <NavBar />
            {children}
            <Footer />
            <Toaster />
          </Web3Provider>
        </RecoilProvider>
      </body>
    </html>
  );
}
